spring.application.name=lead-management


server.port=8081

spring.data.mongodb.uri=mongodb+srv://shrinidhi_user54:srinithi123@cluster101.7jdxmdx.mongodb.net/lead_management?appName=Cluster101
spring.data.mongodb.auto-index-creation=true